spring:
  datasource:
    url: jdbc:h2:mem:judge;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  h2:
    console:
      enabled: true

logging:
  level:
    ai.shodhai.judge: INFO
    org.hibernate.SQL: WARN

server:
  port: 8080
